version: "3.8"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    container_name: es
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kib:
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - "5601:5601"
  hgg:
    build: 
      context: .
      args:
        MM_LICENSE_KEY: $MM_LICENSE
    ports:
      - "10025:10025"
    environment:
      ELASTICSEARCH_URL: http://es:9200

